runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: "17.x"

    - name: Install dependencies
      run: yarn
      shell: bash

    - name: Check lint
      run: yarn lint
      shell: bash

    - name: Run build
      run: yarn build
      shell: bash