runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v6

    - uses: actions/setup-node@v7
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Check lint
      run: pnpm lint
      shell: bash

    - name: Run build
      run: pnpm build
      shell: bash
