name: fetchIcon

on:
  schedule:
    - cron: '*/10 * * * *'

env:
  NOTION_KEY: ${{ secrets.NOTION_KEY }}
  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

jobs:
  fetchIcon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/node-setup
    - run: yarn start:fetchIcon
