name: watchDone

on:
  schedule:
    - cron: '*/10 * * * *'

env:
  NOTION_KEY: ${{ secrets.NOTION_KEY }}
  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

jobs:
  watchDone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        yarn
        yarn build
        yarn start:watchDone