name: watchDone

on:
  schedule:
    # - cron: '*/10 * * * *'
    - cron: '*/1 * * * *'

env:
  NOTION_KEY: ${{ secrets.NOTION_KEY }}
  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

jobs:
  watchDone:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        yarn
        yarn build
        yarn start:watchDone