name: watchDone

on:
  schedule:
    - cron: '*/1 * * * *'

env:
  NOTION_KEY: ${{ secrets.NOTION_KEY }}
  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

jobs:
  watchDone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/node-setup
    - run: |
        yarn start:watchDone