name: watchDone

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  watchDone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        yarn
        yarn build
        yarn start:watchDone